config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/new'
  get 'bookmarks/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'lists#index'
resources :lists, only: [:index, :show, :create, :new] do
  resources :bookmarks, only: [:create, :new]
end
resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie, uniqueness: {scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo
  validates :name, uniqueness: true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true

  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end



  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    redirect_to list_path(@list)
    @bookmark.destroy

  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'new'
    end
  end

  def new
    @list = List.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def background_image(list)
    if list.photo.attached?
      cl_image_path(list.photo.key)
    else
      asset_path('cine.jpeg')
    end
  end
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="d-flex justify-content-center">
  <h1>Add a movie to a list</h1>
</div>
<div class="form">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="page-container">
      <%= render './partials/navbar' %>
      <div id="content-wrap">
        <%= yield %>
      </div>
      <%= render './partials/footer' %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="list-container">
<div class="d-flex justify-content-center m-3 p-3">
  <h1>All your lists</h1>
</div>


<div class="container row justify-content-center">
  <% @lists.each do |list| %>
    <div class="col-4">
      <div class="card">
      <div class="card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= background_image(list) %>)">
      </div>
      <div class="list_title"><%= link_to list.name, list_path(list) %></div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/lists/new.html.erb
<div class="d-flex justify-content-center">
  <h1>Create a new list</h1>
</div>
<div class="form">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="movie-container">
  <div class="title">
    <h1 class="d-flex justify-content-center"><%= @list.name %></h1>
    <h3 class="d-flex justify-content-center"><%= link_to 'Add a movie', new_list_bookmark_path(@list) %><h3>
  </div>


    <% @list.movies.each do |movie| %>
      <div class="movie card d-flex ">
        <div class="d-flex justify-content-space-between">
          <div class="list image_movie p-1 m-1"><%= image_tag movie.poster_url %></div>
          <div>
            <h3 class="info"><%= movie.title %></h3>
            <div class="info"><%= movie.overview %></div>
            <div class="info"><%= movie.rating %></div>
          </div>
        </div>
        <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
        <div class="d-flex justify-content-end">
          <%= link_to 'Remove this movie',  bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?'} %>
        </div>
      </div>
    <% end %>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Colinedsr"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/coline-dusserre/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://i1.sndcdn.com/avatars-YMZvHyxWoLl3AzFg-Ug2F0Q-t500x500.jpg" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to 'Home', lists_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'Add a list', new_list_path%></a>
      </li>
    </ul>
  </div>
</div>